# Title

In [1]:
import mechkit
import numpy as np

In [2]:
np.set_printoptions(
    linewidth=140,
    precision=3,
    # suppress=False,
)

In [3]:
mat = mechkit.material.Isotropic(E=2e6, nu=0.3)
mat = mechkit.material.Isotropic(E=2e6, K=1e6)
mat1 = mechkit.material.Isotropic(M=15, G=5)
mat2 = mechkit.material.Isotropic(C11_voigt=20, C44_voigt=5)

In [4]:
printQueue = [
    "mat.G",
    "mat['E']",
    "mat1['stiffness_voigt']",
    "mat2['stiffness_voigt']",
    "(0.5*mat1 + 0.5*mat2)['stiffness_voigt']",
    "mat1['stiffness_mandel6']",
    "mat1['compliance_mandel6']",
]
for val in printQueue:
    print(val)
    print(eval(val), "\n")

mat.G
857142.8571428572 

mat['E']
2000000.0 

mat1['stiffness_voigt']
[[15.  5.  5.  0.  0.  0.]
 [ 5. 15.  5.  0.  0.  0.]
 [ 5.  5. 15.  0.  0.  0.]
 [ 0.  0.  0.  5.  0.  0.]
 [ 0.  0.  0.  0.  5.  0.]
 [ 0.  0.  0.  0.  0.  5.]] 

mat2['stiffness_voigt']
[[20. 10. 10.  0.  0.  0.]
 [10. 20. 10.  0.  0.  0.]
 [10. 10. 20.  0.  0.  0.]
 [ 0.  0.  0.  5.  0.  0.]
 [ 0.  0.  0.  0.  5.  0.]
 [ 0.  0.  0.  0.  0.  5.]] 

(0.5*mat1 + 0.5*mat2)['stiffness_voigt']
[[17.5  7.5  7.5  0.   0.   0. ]
 [ 7.5 17.5  7.5  0.   0.   0. ]
 [ 7.5  7.5 17.5  0.   0.   0. ]
 [ 0.   0.   0.   5.   0.   0. ]
 [ 0.   0.   0.   0.   5.   0. ]
 [ 0.   0.   0.   0.   0.   5. ]] 

mat1['stiffness_mandel6']
[[15.  5.  5.  0.  0.  0.]
 [ 5. 15.  5.  0.  0.  0.]
 [ 5.  5. 15.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.  0.]
 [ 0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0. 10.]] 

mat1['compliance_mandel6']
[[ 0.08 -0.02 -0.02  0.    0.    0.  ]
 [-0.02  0.08 -0.02  0.    0.    0.  ]
 [-0.02 -0.02  0.08  0.    0.    0.  

In [5]:
mat = mechkit.material.TransversalIsotropic(
    E_l=100.0, E_t=20.0, nu_lt=0.3, G_lt=10.0, G_tt=7.0, principal_axis=[0, 1, 0]
)

In [6]:
printQueue = [
    "mat.compliance_voigt",
    "mat.stiffness_mandel6",
]
for val in printQueue:
    print(val)
    print(eval(val), "\n")

mat.compliance_voigt
[[ 0.05  -0.003 -0.021  0.     0.     0.   ]
 [-0.003  0.01  -0.003  0.     0.     0.   ]
 [-0.021 -0.003  0.05   0.     0.     0.   ]
 [ 0.    -0.    -0.     0.1   -0.    -0.   ]
 [ 0.     0.     0.     0.     0.143  0.   ]
 [ 0.     0.     0.     0.     0.     0.1  ]] 

mat.stiffness_mandel6
[[ 25.677  11.206  11.677   0.      0.      0.   ]
 [ 11.206 106.724  11.206   0.      0.      0.   ]
 [ 11.677  11.206  25.677   0.      0.      0.   ]
 [  0.      0.      0.     20.      0.      0.   ]
 [  0.      0.      0.      0.     14.      0.   ]
 [  0.      0.      0.      0.      0.     20.   ]] 

