# Notation: Converter Numeric

In [1]:
import mechkit
import numpy as np
import sympy as sp
import itertools

In [2]:
np.set_printoptions(
    linewidth=140,
    precision=3,
    # suppress=False,
)
converter = mechkit.notation.Converter()

### Mandel6: symmetric, Mandel9: Mandel6 + asymmetric parts

In [3]:
basics = mechkit.tensors.Basic()

Symmetric identity

In [4]:
print(converter.to_mandel6(basics.I4s))
print(converter.to_mandel9(basics.I4s))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[ 1.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  1.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  1.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00  0.000e+00  0.000e+00 -4.266e-17  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  1.000e+00  0.000e+00  0.000e+00  4.266e-17  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  1.000e+00  0.000e+00  0.000e+00 -4.266e-17]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00 

Asymmetric identity

In [5]:
print(converter.to_mandel6(basics.I4a))
print(converter.to_mandel9(basics.I4a))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00 -4.266e-17  0.000e+00  0.000e+00  1.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  4.266e-17  0.000e+00  0.000e+00  1.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00 

### Convenient autodetection of the notation: Specify only target

In [6]:
tensor = np.ones((3, 3, 3, 3))
mandel6 = converter.to_mandel6(tensor)
# Pass through
print(converter.to_tensor(mandel6))
print(converter.to_mandel6(mandel6))
print(converter.to_mandel9(mandel6))

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]
[[1.    1.    1.    1.414 1.414 1.414]
 [1.    1.    1.    1.414 1.414 1.414]
 [1.    1.    1.    1.414 1.414 1.414]
 [1.414 1.414 1.414 2.    2.    2.   ]
 [1.414 1.414 1.414 2.    2.    2.   ]
 [1.414 1.414 1.414 2.    2.    2.   ]]
[[1.    1.    1.    1.414 1.414 1.414 0.    0.    0.   ]
 [1.    1.    1.    1.414 1.414 1.414 0.    0.    0.   ]
 [1.    1.    1.    1.414 1.414 1.414 0.    0.    0.   ]
 [1.414 1.414 1.414 2.    2.    2.    0.    0.    0.   ]
 [1.414 1.414 1.414 2.    2.    2.    0.    0.    0.   ]
 [1.414 1.414 1.414 2.    2.    2.    0.    0.    0.   ]
 [0.    0.    0.    0.

### Vectorized explicit converter

In [7]:
expl_converter = mechkit.notation.ExplicitConverter()

In [8]:
tensors = np.random.rand(
    3, 3, 3, 3, 5, 2
)  # We have 5 times 2 tensors of fourth order

In [9]:
mandel6s = expl_converter.convert(
    inp=tensors, source="tensor", target="mandel6", quantity="stiffness"
)

In [10]:
for i in range(5):
    for j in range(2):
        print(f"Tensor at position {i}, {j} in Mandel6 notation")
        print(mandel6s[..., i, j])

Tensor at position 0, 0 in Mandel6 notation
[[0.273 0.463 0.028 0.806 0.281 0.703]
 [0.66  0.699 0.157 0.159 1.084 0.941]
 [0.853 0.113 0.637 0.492 0.158 0.2  ]
 [0.981 0.612 0.692 1.112 1.395 1.134]
 [0.577 0.817 0.026 0.652 0.652 0.98 ]
 [1.382 0.946 0.733 1.015 0.886 0.416]]
Tensor at position 0, 1 in Mandel6 notation
[[0.353 0.572 0.928 0.59  0.577 0.952]
 [0.186 0.378 0.715 0.612 0.72  1.053]
 [0.816 0.59  0.723 0.194 1.365 0.192]
 [0.894 0.574 0.539 0.908 0.916 0.555]
 [0.706 0.891 0.25  0.853 1.308 0.629]
 [0.788 0.715 0.437 1.33  0.622 0.86 ]]
Tensor at position 1, 0 in Mandel6 notation
[[0.84  0.047 0.637 0.893 0.439 0.817]
 [0.033 0.386 0.317 0.762 0.691 0.211]
 [0.61  0.243 0.698 1.251 0.63  0.484]
 [0.761 1.062 0.841 0.436 1.451 0.456]
 [1.082 0.798 0.673 1.262 1.164 0.97 ]
 [0.964 0.424 0.741 0.946 0.723 1.248]]
Tensor at position 1, 1 in Mandel6 notation
[[0.067 0.814 0.333 0.522 0.715 1.187]
 [0.246 0.861 0.509 1.277 0.205 0.813]
 [0.739 0.526 0.644 0.309 0.999 0.254]
 [